blockfrost/openapi

- package.json
- swagger.yaml
Clarify that we are talking about the _active_ stake for given epoch.
> epoch: active stake

- package.json
- swagger.yaml
This introduces the multi asset support for tokens.
> assets: init

- swagger.yaml
Adding pagination to the transaction metadata endpoint.
> fix(tx_metadata): adding pagination

- shell.nix
> shell.nix: npm i, build hint

- CHANGELOG.md
> release: 0.1.1 -> 0.1.2

- CHANGELOG.md
- package.json
- swagger.yaml
> release: 0.1.2 -> 0.1.3

- CHANGELOG.md
- package.json
- swagger.yaml
> fix(openapi): invalid_ types integer -> string

- swagger.yaml
Introducing a way to fetch all transactions related to a specific asset.
> feat(assets): list of txs for a specific asset

- CHANGELOG.md
- package.json
- swagger.yaml
> release: 0.1.4 -> 0.1.5

- CHANGELOG.md
- swagger.yaml
Added new items and adjusted some descriptions.
> feat/refactor(release): 0.1.5

- CHANGELOG.md
- swagger.yaml
It might be useful to list the addresses associated with a stake key.
> feat(accounts): adding addresses list

- swagger.yaml
This change makes it more clear how we respond to rate limiting.
> fix(errors): redefining rate limiting errors

- swagger.yaml
We might want to follow https://github.com/input-output-hk/cardano-metadata-submitter and https://github.com/input-output-hk/cardano-wallet/blob/master/specifications/api/swagger.yaml#L586
> fix(assets): adhere to new specification

- CHANGELOG.md
- swagger.yaml
Adding support for the IPFS cluster.
> ipfs: init

- CHANGELOG.md
- package.json
- swagger.yaml
> openapi: missing Cardano tags

- CHANGELOG.md
- swagger.yaml
Might be beneficial to add slot to other endpoints, too.
> feat/fix(txs): add/deprecate parameters

- CHANGELOG.md
- swagger.yaml
This should fix https://github.com/blockfrost/openapi/issues/60.
Added a warning about mangled addresses as well.
> feat(accounts): list of assets on an account

- CHANGELOG.md
- swagger.yaml
Adding the epoch parameters to the latest and txs within a block in the latest.
In the future we might consolidate these with the block/epoch numbers.
> feat(block/epochs): latest params

- CHANGELOG.md
- package.json
- swagger.yaml
Also resolves https://github.com/blockfrost/openapi/issues/60
> release: 0.1.15 -> 0.1.16

- CHANGELOG.md
- swagger.yaml
Adding now the support to query blocks per slot along with epoch slots.
> adding support for blocks per slots

- CHANGELOG.md
- swagger.yaml
Initial work for the `/nutlink` endpoint.
> nutlink: init

- swagger.yaml
> Fix description - plural withdrawals

- swagger.yaml
> Nut.link: fix metadata_url description

- swagger.yaml
Response is string and block hash.
> Fix Address UTXO block field description

- swagger.yaml
As mentioned in the issue this fixes #119 on my side.
> fix data and type mismatch

- CHANGELOG.md
- package.json
- swagger.yaml
This is an initial support for Alonzo features.
> Alozno support

- swagger.yaml
Java and Ruby SDKs are released.
> feat(sdks): adding java and ruby

- CHANGELOG.md
- swagger.yaml
> Switch output_index of tx/utxos from number to integer

- CHANGELOG.md
- swagger.yaml
Adds `/addresses/{address}/utxos/{asset}` endpoint which allows for filtering UTXOs by specific asset.
> feat(addresses): add new endpoint

- CHANGELOG.md
- swagger.yaml
https://github.com/blockfrost/openapi/pull/159
> feat(accounts): new addresses/total endpoint

- swagger.yaml
> docs: add .NET SDK

- openapi.yaml
- src/openapi.yaml
- src/paths/api/utils/txs/evaluate.yaml
Relates to https://github.com/blockfrost/openapi/issues/169.
> feat: /utils/txs/evaluate

- CHANGELOG.md
- openapi.yaml
- src/openapi.yaml
- src/paths/api/scripts/datum/{datum_hash}/cbor.yaml
- src/schemas/scripts/script_cbor.yaml
- src/schemas/scripts/script_datum_cbor.yaml
Adds endpoint for querying CBOR serialised datum(s).
Includes minor fix for scripts CBOR schema.
> CBOR datum

- CHANGELOG.md
> release: 0.1.39 -> 0.1.40

- .github/workflows/check-generated.yaml
> feat(ci): add check generated action

- openapi.yaml
- src/openapi.yaml
Adding reference to `blockfrost-php`.
> docs: adding PHP SDK

- CHANGELOG.md
- openapi.yaml
- package.json
- src/openapi.yaml
Reverts blockfrost/openapi#229
> Revert "release: 0.1.42 -> 0.1.43"

- CHANGELOG.md
- openapi.yaml
- src/schemas/scripts/script_datum.yaml
Reverts blockfrost/openapi#228
> Revert "fix(scripts): json_value -> json"

- CHANGELOG.md
- openapi.yaml
- src/definitions.yaml
- src/functions/custom-schemas/nutlink-address-tickers.ts
- src/functions/custom-schemas/nutlink-ticker.ts
- src/functions/custom-schemas/scripts-json.ts
- src/functions/custom-schemas/txs-metadata.ts
- src/functions/get-schema-for-endpoint.ts
- src/generated-types.ts
- src/schemas/assets/asset.yaml
> refactor: custom schemas + CIP25 v2

- CHANGELOG.md
- openapi.yaml
- package.json
- src/definitions.yaml
- src/functions/index.ts
- src/generated-types.ts
- src/index.ts
- src/schemas/addresses/address_content_extended.yaml
- src/schemas/assets/asset.yaml
- src/schemas/assets/asset_onchain_metadata_cip25.yaml
- test/tests/get-schema-for-endpoint.test.ts
- test/tests/get-schema.test.ts
- test/tests/validate-schema.test.ts
- yarn.lock
> fix: additionalProps in asset

- openapi.yaml
- package.json
- src/definitions.yaml
> release: 0.1.49

- .github/workflows/CI.yaml
- CHANGELOG.md
- openapi.yaml
- src/generated-types.ts
- src/paths/api/nutlink/tickers/{ticker}/index.yaml
- src/paths/api/nutlink/{address}/index.yaml
- src/paths/api/nutlink/{address}/tickers/index.yaml
- src/paths/api/nutlink/{address}/tickers/{ticker}/index.yaml
- src/paths/ipfs/pin/remove/{IPFS_path}/index.yaml
- src/schemas/addresses/address_utxo_content.yaml
Needed for https://github.com/blockfrost/blockfrost-backend-ryo/issues/28
> feat/fix: addresses/utxos - introduce address

- CHANGELOG.md
- openapi.yaml
- src/generated-types.ts
- src/schemas/addresses/address_content_extended.yaml
close https://github.com/blockfrost/openapi/issues/267
> chore(docs): document source of 'decimals' in addresses/addr/extended

- openapi.yaml
- src/definitions.yaml
(cherry picked from commit 1a1b6e22eeca4e6b5cc640351060128d70dd3897)
> chore(testnet): removing

- CHANGELOG.md
- openapi.yaml
- src/functions/schema.ts
- src/schemas/epochs/epoch_stake_content.yaml
- src/schemas/scripts/script_datum.yaml
- test/fixtures/schema.ts
- test/tests/get-schema-for-endpoint.test.ts
- test/tests/get-schema.test.ts
this got rather ugly. I AM SORRY.
> fix(getSchemaForEndpoint): fastify serializer compatible schema

- openapi.yaml
- src/definitions.yaml
- src/generated-types.ts
- src/paths/api/mempool/addresses/{address}/index.yaml
- src/paths/api/mempool/index.yaml
- src/paths/api/mempool/{hash}/index.yaml
- src/paths/api/tx/submit.yaml
- src/paths/api/utils/txs/evaluate/index.yaml
- src/paths/api/utils/txs/evaluate/utxos.yaml
- src/paths/ipfs/add.yaml
- src/paths/ipfs/gateway/{IPFS_path}/index.yaml
- src/paths/ipfs/pin/list/index.yaml
- src/paths/ipfs/pin/list/{IPFS_path}/index.yaml
- src/paths/ipfs/pin/remove/{IPFS_path}/index.yaml
Closes #289
If we use a additional tag we get a new category which clutters the menu. If we use [Redoc specific `x-traitTag`](https://github.com/Redocly/redoc/blob/main/docs/redoc-vendor-extensions.md#x-traittag) we get an empty category. Opted to not use any of these.
> Document hosted endpoints

- CHANGELOG.md
- openapi.json
- openapi.yaml
- src/definitions.yaml
- src/generated-types.ts
- src/paths/api/txs/{hash}/required_signers.yaml
- src/schemas/txs/tx_content_required_signers.yaml
- test/tests/__snapshots__/get-schema-for-endpoint.test.ts.snap
> Add /txs/{hash}/required_signers endpoint

- docs/index.html
chore: try reload
chore: try reload
chore: try reload
chore: try reload
chore: try reload
> chore: try reload
