blockfrost/openapi

swagger.yaml
Epochs improvements and fixes.
Improvements:
- introduced `first_block_time` and `last_block_time` which are first and last block times of the queried epoch
- introduced `active_stake` which is the sum of amount staked in queried epoch
Fixes:
- `start_time` and `end_time` times will correctly reflect epoch times (previously, first and last block times were displayed, respectively)
! Breaking change - unify terminology.
- `blocks_count` -> `block_count`
- `txs_count -> tx_count`
- `txs_sum` -> `output`
- `fees_sum` -> `fees`
Affected endpoints: `/epochs/latest`, `/epochs/{number}`, `/epochs/{number}/next`, `/epochs/{number}/previous`.
=> !fix/feat(epochs): fix start/end times, introduce block times and active_stake

swagger.yaml
In `pools` endpoint, we are showing current live pledge but the proprieties is wrongly name `active_pledge`.
=> pools: rename active_pledge to live_pledge

swagger.yaml
Renaming `acronym` to `ticker` after this change has bee made in the metadata registry.
=> assets: renaming acronym to ticker

swagger.yaml
Thanks to Samuel from IOG, I finally discovered the missing item field that were causing an problem with the HTML rendering.
=> metadata/labels: typo in missing items

swagger.yaml
```
Errors:
- attribute components.schemas.tx_metadata_label_json.items is missing
```
Not sure about the impact of this on backend side.
=> fix missing attribute error schemas.tx_metadata_label_json.items

swagger.yaml
Following up on https://github.com/blockfrost/openapi/pull/10 - cc @sorki - Either this or leaving `type` completely out seems to fix the issue. We might want to keep `array` in, since it is a valid JSON. Would this work for you?
There's a further discussion on types: https://github.com/OAI/OpenAPI-Specification/issues/1657
According to https://swagger.io/docs/specification/data-models/data-types/, `AnyValue` should be equivalent to:
```
anyOf:
- type: string
- type: number
- type: integer
- type: boolean
- type: array
items: {}
- type: object
```
=> fix(metadata): json_metadata type

swagger.yaml
Reword `/pools` description `List of active stake pools.` -> `List of registered stake pools.` to better match the actual output. All pools, including those retiring but not yet retired, are being displayed in this call.
Feature: Allow searching by hexadecimal Pool ID since it's still quite popular.
=> fix/feat(pools): reword desc, add hex search

swagger.yaml
Removing the `unit` field from the asset's metadata.
=> fix(assets): removing the unit field

CHANGELOG.md, swagger.yaml
Moving the submit of transaction to support CBOR encoded payload instead of the binary blob.
=> !feat(tx/submit): moving to a base64 encoded transaction

swagger.yaml
Documenting that our API is case sensitive and we prefer lower case use for HEX. 
SDKs needs to make sure they are passing it as such.
=> chore(docs): hex encoded values

swagger.yaml
Enuming the possible state of a pinned item.
=> chore(ipfs): enum the state of a pin

swagger.yaml
This fixes the API url that is shown in examples.
=> fix(ipfs): correct API uri

CHANGELOG.md, swagger.yaml
There is an on-going discussion for a community on-chain standard that is already widely used at https://github.com/cardano-foundation/CIPs/pull/85
This metadata is stored under the label `721` of the minting transaction, under the policy id and token name.
=> feat(assets): Adding on-chain metadata

CHANGELOG.md
```
`onchain_metadata` to `/assets/{asset}` endpoint
```
was incorrectly placed into `changed`, but should have been in `added`.
=> fix(changelog): transfer one item from changed to added

swagger.yaml
An example documenting how to transform the transaction built by `cardano-cli` to a serialized tx.
=> docs(tx/submit): adding an example for cardano-cli

swagger.yaml
So it's less tricky to discover when following e.g. `IPFS » Add` -> `Authorizations: ApiKeyAuth` link.
aed16e7  resolves a collision in ToC.
=> Documentation improvements

swagger.yaml
Maybe even:
```diff
- All time and timestamp related fields are in seconds of UNIX time.
+ All time and timestamp related fields (except `server_time`) are in seconds of UNIX time.
```
=> Couple inconsistencies discovered recently

CHANGELOG.md, swagger.yaml
https://github.com/ipfs/go-ipfs/issues/4008#issuecomment-311198782
Also the decription is changed as it returns resulting IPFS node
size according to https://github.com/ipfs/go-ipfs/pull/4082
=> ipfs: fix ipfs/add response size type to string

swagger.yaml
Noticed it's a `string` instead of some hash.
=> fix(txs): add data_hash example for `txs/{hash}/utxos` inputs

src/schemas/accounts/account_content.yaml
Via https://github.com/blockfrost/blockfrost-haskell/issues/16
=> fix: account info active_epoch can be null

openapi.yaml, src/paths/api/accounts/{stake_address}/addresses/total.yaml
The spec published here https://docs.blockfrost.io/ seems to throw some errors:
https://github.com/ozerogames/openapi/blob/master/openapi.yaml#L2258
vs
https://github.com/ozerogames/openapi/blob/master/openapi.yaml#L2244
This PR might fix it, idk, maybe, probably.
=> Use `stake_address` in path in total.yaml

openapi.yaml, src/paths/api/nutlink/{address}/tickers/index.yaml, src/schemas/assets/asset.yaml
1. extra in-path element reported by swagger editor `https://editor.swagger.io/`
2. missing `items` for type array reported by OpenAPI Tools
```sh
> docker run --rm openapitools/openapi-generator-cli validate -i https://raw.githubusercontent.com/blockfrost/openapi/master/openapi.yaml
Validating spec (https://raw.githubusercontent.com/blockfrost/openapi/master/openapi.yaml)
Errors:
- attribute components.schemas.asset.items is missing
```
=> Remove unused path element, specify array item type

CHANGELOG.md, openapi.yaml, src/schemas/pools/pool_list_extended.yaml
missing `hex`.
Also add warning emoji to the only incompatible change of last HF.
=> Fix `/pools/extended` example

CHANGELOG.md, openapi.yaml, package.json, src/definitions.yaml, src/functions/metadata.ts, src/generated-types.ts, src/index.ts, src/schemas/assets/asset_onchain_metadata_cip68_ft_333.yaml, src/schemas/assets/asset_onchain_metadata_cip68_nft_222.yaml, src/types/metadata.ts, test/fixtures/metadata.ts, test/tests/metadata.test.ts
few things I am not sure about:
- [CIP68 specifies description field within metadata for the NFT standard](https://cips.cardano.org/cips/cip68/#metadata) as ``` ? description : bounded_bytes, ; UTF-8```, but [CIP25 also allows an array](https://cips.cardano.org/cips/cip25/#generalstructure). Right now array won't pass the validation. ✅ 
- what about (future) CIP68 metadata with version > 1? Currently version other than 1 won't pass the validation. ✅  (discussed)
- Should additional fields within the metadata that are not defined in CIP25 (or off-chain metadata standard) fail the validation? Currently they will pass. ✅  (CIP25 allows additional fields)
- Regarding implementation in RYO: If CIP68 metadata (extracted from datum) are present, but fail the validation. Should they be returned …
=> chore: cip68

CHANGELOG.md, openapi.yaml, package.json, src/definitions.yaml, src/functions/schema.ts, src/generated-types.ts, src/index.ts, src/paths/ipfs/gateway/{IPFS_path}/index.yaml, test/fixtures/schema.ts, test/tests/__snapshots__/get-schema-for-endpoint.test.ts.snap, test/tests/get-schema-for-endpoint.test.ts, test/tests/get-schema.test.ts, yarn.lock
- workaround for https://github.com/blockfrost/openapi/issues/296
- multiple fixes for fast-json-stringify schema generator
- fixed /ipfs/gateway/{IPFS_path} schema
- snapshot tests for FULL schema for every endpoint
pre openapi 3.1. schema snapshot for reference
https://gist.github.com/slowbackspace/1487dfeec9385507bd36367340e85512
(copy paste it instead of current snapshot to see changes)
=> fix: fastify schema, release 0.1.57

.prettierrc, CHANGELOG.md, src/functions/metadata.ts, test/fixtures/metadata.ts
resolves https://github.com/blockfrost/openapi/issues/375
=> chore: allow non-utf8 asset names in onchain metadata cip25v1

blockfrost-openapi.yaml, docs/blockfrost-openapi.yaml, openapi.yaml, src/paths/ipfs/add.yaml, src/paths/ipfs/gateway/{IPFS_path}/index.yaml, src/paths/ipfs/pin/add/{IPFS_path}/index.yaml, src/paths/ipfs/pin/list/index.yaml, src/paths/ipfs/pin/list/{IPFS_path}/index.yaml, src/paths/ipfs/pin/remove/{IPFS_path}/index.yaml
I believe
- because no `x-codeSamples` are provided for the IPFS endpoints (except `POST /ipfs/add`)
- then the site generated usage examples shown via https://docs.blockfrost.io/ default to showing the wrong path 
- Shown is `https://cardano-mainnet.blockfrost.io`,  the correct path is `https://ipfs.blockfrost.io/api/v0/ipfs`.
- this is not the case for `POST /ipfs/add` because an example `x-codeSamples` is given.
- I have added a `x-codeSamples` example for each IPFS endpoint, with the correct base path (`https://ipfs.blockfrost.io/api/v0/ipfs`)
- Incorrect examples being given by defualt can be confusing for people trying to use the IPFS endpoints
- I was stuck for an embarrassing amount of time...
- This might not be the best way to fix this, as this only fixes the issue for the …
=> Fix: IPFS examples
